# modified from https://github.com/jgm/pandoc/blob/master/.github/workflows/ci.yml
name: Haskell library and example

on:
  push:
    branches:
    - '**'
    paths-ignore: []
  pull_request:
    paths-ignore: []

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.4.4', '9.2.7', '9.0.2']
        cabal: ['3.10.1.0']
        os: [ubuntu-latest]
    name: Cabal with GHC ${{ matrix.ghc }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    # declare/restore cached things
    # caching doesn't work for scheduled runs yet
    # https://github.com/actions/cache/issues/63

    - name: Cache cabal global package db
      id:   cabal-global
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-global-${{ hashFiles('cabal.project') }}

    - name: Cache cabal work
      id:   cabal-local
      uses: actions/cache@v2
      with:
        path: |
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-local

    - name: Install dependencies
      run: |
          cabal update
          cabal build all --dependencies-only --enable-tests --disable-optimization
    - name: Build
      run: |
          cabal build all --enable-tests --disable-optimization 2>&1 | tee build.log

    - uses: actions/setup-node@v3
      with:
        node-version: "18.x"
    - uses: purescript-contrib/setup-purescript@main

    - name: Test
      run: |
          cabal test all --disable-optimization
